#!/bin/sh
# echo "Clean results dir."
# rm results/*
echo "Clean highorder_results dir."
rm highorder_results/*
echo "Start computations"
# build/bin/dgalerkin doc/config/Cube.conf
# build/bin/dgalerkin  doc/config/Sphere.conf
# build/bin/dgalerkin  doc/config/Urban_3D.conf
# build/bin/dgalerkin  doc/config/land.conf

# build/bin/dgalerkin doc/config/Square.conf

#build/bin/dgalerkin doc/config/Square.json

# build/bin/dgalerkin cases/2d_hilltop/2d_hilltop.json
#build/bin/dgalerkin cases/2d_hilltop/2d_hilltop.conf
#build/bin/dgalerkin cases/2d_hilltop/rectangle.json
#build/bin/dgalerkin cases/2d_hilltop/bump.json

# build/bin/dgalerkin doc/config/Gaussian2d.conf
build/bin/dgalerkin doc/config/Gaussian3d.conf